### ISSUE TITLE
Connnection fails at random epoch

### ISSUE THREAD

**Issue by balakhonoff** [catalyst-team/alchemy#10]
Hi!
After updating to 20.3 from 20.4 I am getting very stable connection error at random epoch. I will attach the stack trace later...

**Comment by balakhonoff** [comment]
Here is the traceback:
`5/25 * Epoch 5 (_base): lr=1.307e-06 | momentum=0.9000
5/25 * Epoch 5 (train): auc/_mean=0.9095 | auc/class_0=0.9095 | loss=0.2496
5/25 * Epoch 5 (valid): auc/_mean=0.8563 | auc/class_0=0.8563 | loss=0.3610
6/25 * Epoch (train):  88% 406/459 [01:27<00:11,  4.62it/s, loss=0.427]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ce2e22d90>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/kb/jig_env/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='log.alchemy.host', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ce2e22d90>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kb/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/kb/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kb/jig_env/lib/python3.7/site-packages/alchemy/logger.py", line 78, in _run_worker
    requests.post(self._url, json=batch, headers=headers)
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/kb/jig_env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='log.alchemy.host', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5ce2e22d90>: Failed to establish a new connection: [Errno 110] Connection timed out'))

6/25 * Epoch (train): 100% 459/459 [01:39<00:00,  4.62it/s, loss=0.027]
6/25 * Epoch (valid): 100% 209/209 [00:14<00:00, 14.75it/s, loss=0.025]
[2020-04-19 18:36:30,050] `

**Comment by balakhonoff** [comment]
The epoch could be the other, and to reproduce one can run the notebook https://yadi.sk/d/Agr5JkPH-SppuA

**Comment by balakhonoff** [comment]
I use cuda 10.2 (which one is the recommended?)
result of pip freeze:
absl-py==0.9.0
alchemy==20.4
astor==0.8.1
astunparse==1.6.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.4
boto3==1.12.39
botocore==1.15.39
cachetools==4.1.0
catalyst==20.4.1
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.1
crc32c==2.0
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
deprecation==2.0.7
docutils==0.15.2
entrypoints==0.3
filelock==3.0.12
gast==0.3.3
gitdb==4.0.4
GitPython==3.1.1
google-auth==1.13.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.28.1
h5py==2.10.0
idna==2.8
imageio==2.8.0
importlib-metadata==1.6.0
ipykernel==5.2.0
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.16.0
Jinja2==2.11.2
jmespath==0.9.5
joblib==0.14.1
jsonschema==3.2.0
jupyter-client==6.1.2
jupyter-core==4.6.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.2.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
networkx==2.4
nltk==3.5
notebook==6.0.3
numpy==1.18.2
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.2.1
packaging==20.3
pandas==1.0.3
pandocfilters==1.4.2
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==6.2.2
plotly==4.6.0
prometheus-client==0.7.1
prompt-toolkit==3.0.5
protobuf==3.11.3
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.0
regex==2020.4.4
requests==2.22.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.0
s3transfer==0.3.3
sacremoses==0.0.35
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
sentencepiece==0.1.85
six==1.14.0
sklearn==0.0
smmap==3.0.2
tb-nightly==2.3.0a20200422
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post3
tensorboardX==2.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tf-estimator-nightly==2.3.0.dev2020042201
tf-nightly==2.2.0.dev20200422
tokenizers==0.7.0rc5
torch==1.4.0
torchvision==0.5.0
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
transformers==2.8.0
urllib3==1.25.8
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0
